# Functional  programing
- lambda
- map
- filter
- all these are anonymous functions

###  lambda  syntax : lambda argument:expression

In [6]:
x = lambda a, b : a * b

print(x(5, 6))


30


### map syntax : map(function,iterable1,iterable2,...)

In [22]:
l1=[1,2,3,4,5,6,7,8,9,10]
l=list(map(lambda x:x**3,range(1,11)))
print(l)

[1, 8, 27, 64, 125, 216, 343, 512, 729, 1000]


## program-1

In [15]:
l=[]
m=int(input("enter no of names:"))
for i in range(m):
    n=input("enter name:")
    l.append(n)
k=map(lambda x:x.upper(),l)
print(list(k))

enter no of names:2
enter name:usha
enter name:sree
['USHA', 'SREE']


In [20]:
x=list(map(str,input().split()))
k=map(lambda x:x.upper(),x)
print(list(k))

usha sree sowmya
['USHA', 'SREE', 'SOWMYA']


## filter

In [24]:
l=list(filter(lambda x:x>5,range(1,11)))
print(list(l))

[6, 7, 8, 9, 10]


# numpy
- numerical python
- create arrays(general and random)
- 2 dimensional arrays
- sceintfiic notation
- comprised of math and random
- main purpose is creating array

In [27]:
import numpy as np

In [28]:
print(dir(np),end=" ")

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__file__', '__getattr__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_distributor_init', '_globals', '_mat', '_pytes

In [31]:
ar=np.array("hello welcome to python".split())
print(ar)

['hello' 'welcome' 'to' 'python']


In [34]:
ar=np.array([i for i in range(1,11)])
print(ar)

[ 1  2  3  4  5  6  7  8  9 10]


In [38]:
ar=np.array({1,2,3,3,3,3})
print(ar)

{1, 2, 3}


In [43]:
l=np.array([(1,2),(4,6),("usha","sree")])
print(l)

[['1' '2']
 ['4' '6']
 ['usha' 'sree']]


In [45]:
l=np.array(range(10))
l

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
l=np.array(range(11,30))
l

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29])

#### creating array using arange()method
- range()-python
- arange()-numpy
- arange(lw,up,step)-inclusive

In [49]:
l=np.arange(10)# used to create array 
l

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
l=np.arange(10,40,5)
l

array([10, 15, 20, 25, 30, 35])

### creating arrays wiith arange().reshape()
- row matrix 2d array using reshape()
- based on the size of array
- np.arange(30).reshape(1,30)#row matrix
- (5,6)(2,15),(3,10),(30,1)

In [62]:
l=np.arange(30).reshape(-1,6)
l

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

### random
- random.randint()
 - random.randint(,)
    - random.randint(,,)
     - random.randint(,())
- random.random(())
- random.rand(,)
- random.randn(,)

In [81]:
r=np.random.randint(10)
print(r)
l=np.random.randint(10,40)
print(l)
k=np.random.randint(10,50,6)
print(list(k))
m=np.random.randint(10,100,(2,4))
print(m)
j=np.random.randint(10,50,12).reshape(3,4)
print(j)

5
25
[16, 35, 18, 23, 34, 15]
[[68 74 31 86]
 [41 25 48 97]]
[[46 18 36 39]
 [42 21 18 25]
 [10 21 37 10]]


In [84]:
rn=np.random.random((2,4))
print(rn)

[[0.51143414 0.4330695  0.62658614 0.42859648]
 [0.69162454 0.92682674 0.32643503 0.79192386]]


In [87]:
rd=np.random.rand(3,2)
print(rd)

[[0.63767627 0.68192832]
 [0.59958632 0.49109658]
 [0.03904368 0.32750362]]


## linspace

In [88]:
print(np.linspace(10,20,5))
print(np.linspace(3,9,4))

[10.  12.5 15.  17.5 20. ]
[3. 5. 7. 9.]


## full and fill

In [90]:
o=np.ones((2,3))
print(o)

[[1. 1. 1.]
 [1. 1. 1.]]


In [93]:
o=np.zeros((2,3))
print(o)

[[0. 0. 0.]
 [0. 0. 0.]]


In [94]:
f=np.full((3,2),5)
print(f)
o.fill(9)
print(o)

[[5 5]
 [5 5]
 [5 5]]
[[9. 9. 9.]
 [9. 9. 9.]]


In [100]:
st=np.array([['hi','hello'],[12,34],[6.3,7.8]])
print(st)
type(st)
print(st.dtype)
print(np.diag(st))
print(np.diag([1,2,3,4]))
print(np.eye(4))

[['hi' 'hello']
 ['12' '34']
 ['6.3' '7.8']]
<U5
['hi' '34']
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### slicing
- ar[:] lw,up
- ar[row:col]
- 

In [125]:
arr=np.arange(25).reshape(5,5)
print(arr)
arr[2][2]
arr[3:5,1:4]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


array([[16, 17, 18],
       [21, 22, 23]])

In [123]:
e=np.random.randint(10,100,(4,4))
print(e[:])
print(e[2:,:3])
print(e[2:])
print(e[:1])
print(e[:5,1:])
print(e[3:,:2])

[[68 24 45 40]
 [11 91 75 46]
 [65 20 88 96]
 [75 69 54 39]]
[[65 20 88]
 [75 69 54]]
[[65 20 88 96]
 [75 69 54 39]]
[[68 24 45 40]]
[[24 45 40]
 [91 75 46]
 [20 88 96]
 [69 54 39]]
[[75 69]]


In [124]:
m=np.random.randint(30,60,(5,5))
print(m)

[[35 32 49 52 34]
 [56 38 51 59 31]
 [47 41 53 45 56]
 [54 47 42 36 54]
 [40 45 52 53 59]]


In [128]:
print(arr+m)
print(".........")
print(m-arr)
print(".......")
print(arr*m)
print("........")
print(m/arr)
print(".....")
print(np.min(m))
print(".........")
print(np.max(ar))

[[35 33 51 55 38]
 [61 44 58 67 40]
 [57 52 65 58 70]
 [69 63 59 54 73]
 [60 66 74 76 83]]
.........
[[35 31 47 49 30]
 [51 32 44 51 22]
 [37 30 41 32 42]
 [39 31 25 18 35]
 [20 24 30 30 35]]
.......
[[   0   32   98  156  136]
 [ 280  228  357  472  279]
 [ 470  451  636  585  784]
 [ 810  752  714  648 1026]
 [ 800  945 1144 1219 1416]]
........
[[        inf 32.         24.5        17.33333333  8.5       ]
 [11.2         6.33333333  7.28571429  7.375       3.44444444]
 [ 4.7         3.72727273  4.41666667  3.46153846  4.        ]
 [ 3.6         2.9375      2.47058824  2.          2.84210526]
 [ 2.          2.14285714  2.36363636  2.30434783  2.45833333]]
.....
31
.........
{1, 2, 3}


<ipython-input-128-1bfa4d2322c6>:7: RuntimeWarning: divide by zero encountered in true_divide
  print(m/arr)


In [131]:
print(np.mean(m))
print("over")
print(np.std(m))
print("completed")
print(np.median(arr))
print("nxt step")
print(arr.dot(m))

46.44
over
8.47622557510122
completed
12.0
nxt step
[[ 472  441  491  469  541]
 [1632 1456 1726 1694 1711]
 [2792 2471 2961 2919 2881]
 [3952 3486 4196 4144 4051]
 [5112 4501 5431 5369 5221]]


## broadcasting
- applying a single value on iterable

In [133]:
print(arr+5)
print("....")
print(arr*4)
print("....")
print(arr/3)

[[ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]
....
[[ 0  4  8 12 16]
 [20 24 28 32 36]
 [40 44 48 52 56]
 [60 64 68 72 76]
 [80 84 88 92 96]]
....
[[0.         0.33333333 0.66666667 1.         1.33333333]
 [1.66666667 2.         2.33333333 2.66666667 3.        ]
 [3.33333333 3.66666667 4.         4.33333333 4.66666667]
 [5.         5.33333333 5.66666667 6.         6.33333333]
 [6.66666667 7.         7.33333333 7.66666667 8.        ]]


##  logarithm and exponentials

In [143]:
np.log(2)

0.6931471805599453

In [144]:
np.log([2,3,4])

array([0.69314718, 1.09861229, 1.38629436])

In [145]:
print(np.exp(3))

20.085536923187668


In [149]:
print(np.exp(1.09861229))

3.000000003995671


In [151]:
def greater(a,b):
    if(a>b):
        return a
    else:
        return b
greater([5,6,7],[4,5,7])

[5, 6, 7]

## pandas
- means panel data
- one of the data science packages
- used for data manupulation,analysis and cleaning
- contains mainly two data structures in it
   - 1.series
   - 2.data frames
- sequence of data
- dataframe is a data with row and column

In [155]:
import pandas as pd
pd.__version__

'1.1.3'

### series
- syntax : pd.Series(data,index,dtype)

In [158]:
s='welcome'
pd.Series(s)

0    welcome
dtype: object

In [161]:
s1='hi hello gud mrng'.split()
pd.Series(s1)
pd.Series(s1,index={1,2,3,4})

1       hi
2    hello
3      gud
4     mrng
dtype: object

In [163]:
l=[1,'usha',3.1]
pd.Series(l,index={'int','str','float'})

int         1
str      usha
float     3.1
dtype: object

In [164]:
t=('a','i','e','o','u')
pd.Series(t,index=['v1','v2','v3','v4','v5'])

v1    a
v2    i
v3    e
v4    o
v5    u
dtype: object

In [170]:
d={1:'u',2:3,3:4.5,'name':'usha'}
pd.Series(d,index=d)

1          u
2          3
3        4.5
name    usha
dtype: object

# data frames

In [171]:
st='hello hi hwr u'.split()
pd.DataFrame(st,index={1,2,3,4})

0
1  hello
2     hi
3    hwr
4      u

In [176]:
li=[[1,2,3],[4,5,6]]
pd.DataFrame(li,index=['list1','list2'])

0  1  2
list1  1  2  3
list2  4  5  6

In [181]:
di={1:1,2:3.1,3:"name",4:"usha"}
pd.DataFrame(di,index=[1])

1    2     3     4
1  1  3.1  name  usha

In [183]:
dic={'names':['usha','sowmya','bhavya','sushma'],'marks':[100,90,80,70],'id':[1,2,3,4]}
pd.DataFrame(dic,index=['stu1','stu2','stu3','stu4'])

names  marks  id
stu1    usha    100   1
stu2  sowmya     90   2
stu3  bhavya     80   3
stu4  sushma     70   4

In [184]:
d={'key1':('u','s','h'),'key2':(6,3,0)}
pd.DataFrame(d,index=[1,2,3])

key1  key2
1    u     6
2    s     3
3    h     0

In [196]:
s=pd.Series(np.random.randint(20,40,8))
print(s)
s[2::3]

0    37
1    38
2    35
3    34
4    34
5    37
6    24
7    32
dtype: int32


2    35
5    37
dtype: int32

## dataframes analysis and manipulation

In [204]:
df1=pd.DataFrame({'month':[2,3,4,5],'days':[28,31,30,31]},index=[2001,2020,2003,2004])
df1

month  days
2001      2    28
2020      3    31
2003      4    30
2004      5    31

In [201]:
df2=pd.DataFrame({'n_p':[3,4,5,6],'n_h':[20,34,56,78]},index=[2001,2020,2034,2056])
df2

n_p  n_h
2001    3   20
2020    4   34
2034    5   56
2056    6   78

In [205]:
df1.join(df2)

month  days  n_p   n_h
2001      2    28  3.0  20.0
2020      3    31  4.0  34.0
2003      4    30  NaN   NaN
2004      5    31  NaN   NaN

In [206]:
df2.join(df1)

n_p  n_h  month  days
2001    3   20    2.0  28.0
2020    4   34    3.0  31.0
2034    5   56    NaN   NaN
2056    6   78    NaN   NaN

In [207]:
df3=pd.DataFrame({'a':[30,40,50,60],'b':[2,3,5,7]},index=[2001,2002,2003,2004])
df3

a  b
2001  30  2
2002  40  3
2003  50  5
2004  60  7

In [210]:
df4=pd.DataFrame({'a':[30,40,80,90],'b':[2,3,9,5]},index=[2001,2002,20030,20040])
df4

a  b
2001   30  2
2002   40  3
20030  80  9
20040  90  5

In [212]:
df3.merge(df4)

a  b
0  30  2
1  40  3

In [214]:
con=pd.concat([df1,df2])
con

month  days  n_p   n_h
2001    2.0  28.0  NaN   NaN
2020    3.0  31.0  NaN   NaN
2003    4.0  30.0  NaN   NaN
2004    5.0  31.0  NaN   NaN
2001    NaN   NaN  3.0  20.0
2020    NaN   NaN  4.0  34.0
2034    NaN   NaN  5.0  56.0
2056    NaN   NaN  6.0  78.0

In [215]:
dates=pd.date_range('2020-10-20','2020-10-25')
pd.Series(dates,index=['day1','day2','day3','day4','day5','day6'])

day1   2020-10-20
day2   2020-10-21
day3   2020-10-22
day4   2020-10-23
day5   2020-10-24
day6   2020-10-25
dtype: datetime64[ns]

In [224]:
marks_df=pd.read_csv('marks.csv')
marks_df

name  eng   sci
0    a   10  20.0
1    b   20  30.0
2    c   30  40.0
3    d   40  50.0
4    e   50  60.0
5    f   34   NaN
6    g  344  56.0

In [225]:
marks_df.head()

name  eng   sci
0    a   10  20.0
1    b   20  30.0
2    c   30  40.0
3    d   40  50.0
4    e   50  60.0

In [226]:
marks_df.tail()

name  eng   sci
2    c   30  40.0
3    d   40  50.0
4    e   50  60.0
5    f   34   NaN
6    g  344  56.0

In [227]:
marks_df.head(3)

name  eng   sci
0    a   10  20.0
1    b   20  30.0
2    c   30  40.0

In [228]:
marks_df.tail(4)

name  eng   sci
3    d   40  50.0
4    e   50  60.0
5    f   34   NaN
6    g  344  56.0

In [229]:
pd.read_csv('marks.csv',header=None)

0    1    2
0  name  eng  sci
1     a   10   20
2     b   20   30
3     c   30   40
4     d   40   50
5     e   50   60
6     f   34  NaN
7     g  344   56

In [230]:
pd.read_csv('marks.csv',usecols=['name','eng'])

name  eng
0    a   10
1    b   20
2    c   30
3    d   40
4    e   50
5    f   34
6    g  344

In [231]:
df=pd.read_csv('marks.csv',names=['N','E','S'])
df

N    E    S
0  name  eng  sci
1     a   10   20
2     b   20   30
3     c   30   40
4     d   40   50
5     e   50   60
6     f   34  NaN
7     g  344   56

In [233]:
df['S']

0    sci
1     20
2     30
3     40
4     50
5     60
6    NaN
7     56
Name: S, dtype: object

In [234]:
marks_df.columns

Index(['name', 'eng', 'sci'], dtype='object')

In [235]:
marks_df.info

<bound method DataFrame.info of   name  eng   sci
0    a   10  20.0
1    b   20  30.0
2    c   30  40.0
3    d   40  50.0
4    e   50  60.0
5    f   34   NaN
6    g  344  56.0>

In [236]:
marks_df.describe()

eng        sci
count    7.000000   6.000000
mean    75.428571  42.666667
std    119.139774  15.577762
min     10.000000  20.000000
25%     25.000000  32.500000
50%     34.000000  45.000000
75%     45.000000  54.500000
max    344.000000  60.000000

In [237]:
marks_df.dtypes

name     object
eng       int64
sci     float64
dtype: object

In [239]:
marks_df.index

RangeIndex(start=0, stop=7, step=1)

In [240]:
marks_df.shape

(7, 3)

In [241]:
marks_df.shape[1]

3

In [242]:
marks_df.shape[0]

7

In [245]:
marks_df.sort_values('sci')

name  eng   sci
0    a   10  20.0
1    b   20  30.0
2    c   30  40.0
3    d   40  50.0
6    g  344  56.0
4    e   50  60.0
5    f   34   NaN

In [247]:
marks_df['college']='abc'
marks_df

name  eng   sci college
0    a   10  20.0     abc
1    b   20  30.0     abc
2    c   30  40.0     abc
3    d   40  50.0     abc
4    e   50  60.0     abc
5    f   34   NaN     abc
6    g  344  56.0     abc

In [249]:
marks_df.sample(3)

name  eng   sci college
2    c   30  40.0     abc
6    g  344  56.0     abc
5    f   34   NaN     abc

In [255]:
marks_df.eng.value_counts()

30     1
10     1
40     1
34     1
20     1
344    1
50     1
Name: eng, dtype: int64

In [256]:
marks_df.isnull()

name    eng    sci  college
0  False  False  False    False
1  False  False  False    False
2  False  False  False    False
3  False  False  False    False
4  False  False  False    False
5  False  False   True    False
6  False  False  False    False

In [259]:
marks_df.dropna()

name  eng   sci
0    a   10  20.0
1    b   20  30.0
2    c   30  40.0
3    d   40  50.0
4    e   50  60.0
6    g   34  56.0